In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("Downloads\customer_shopping_behavior.csv")

In [4]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [6]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [7]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [8]:
df["Review Rating"] = df.groupby("Category")["Review Rating"].transform(lambda x: x.median())

In [9]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [10]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.7,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.7,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.7,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.8,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,3.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [11]:
df.columns = df.columns.str.lower()

In [12]:
df.columns = df.columns.str.replace(' ', '_')

In [13]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [18]:
label = ["young","adult","senior","aged"]
df["age_group"]= pd.qcut(df["age"],q=4 , labels = label )

In [19]:
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount_(usd),location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases,frequency,age_group
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.7,Yes,Express,Yes,Yes,14,Venmo,Fortnightly,14,senior
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.7,Yes,Express,Yes,Yes,2,Cash,Fortnightly,14,young
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.7,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly,7,senior
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.8,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly,7,young
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,3.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually,365,senior

In [20]:
df['frequency_of_purchases'].unique()

array(['Fortnightly', 'Weekly', 'Annually', 'Quarterly', 'Bi-Weekly',
       'Monthly', 'Every 3 Months'], dtype=object)

In [21]:
frequency = {
    "Fortnightly": 14,
    "Weekly": 7,
    "Bi-Weekly": 14,
    "Monthly": 30,
    "Quarterly": 90,
    "Every 3 Months": 90,
    "Annually": 365
}

df["frequency"] = df["frequency_of_purchases"].map(frequency)

In [22]:
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount_(usd),location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases,frequency,age_group
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.7,Yes,Express,Yes,Yes,14,Venmo,Fortnightly,14,senior
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.7,Yes,Express,Yes,Yes,2,Cash,Fortnightly,14,young
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.7,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly,7,senior
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.8,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly,7,young
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,3.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually,365,senior

In [23]:
df['purchase_amount'] = df['purchase_amount_(usd)']

In [24]:
df.drop("purchase_amount_(usd)", inplace =True, axis = 1)

In [79]:
!pip install psycopg2-binary sqlalchemy pandas

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.12-cp313-cp313-win_amd64.whl.metadata (5.1 kB)
Requirement already satisfied: sqlalchemy in c:\users\acer\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: pandas in c:\users\acer\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: greenlet>=1 in c:\users\acer\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\acer\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\acer\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\acer\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\acer\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\acer\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\acer\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading psycopg2_binary-2.9.12-cp313-cp313-win_amd64.whl (2.8 MB)
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   ------- -------------------------------- 0.5/2.8 MB 1.4 MB/s eta 0:00:02
   ----------- ---------------------------- 0.8/2.8 MB 1.2 MB/s eta 0:00:02
   ----------- ---------------------------- 0.8/2.8 MB 1.2 MB/s eta 0:00:02
   --------------- ------------------------ 1.0/2.8 MB 964.0 kB/s eta 0:00:02
   ------------------- -------------------- 1.3/2.8 MB 940.9 kB/s eta 0:00:02
   ------------------- -------------------- 1.3/2.8 MB 940.9 kB/s eta 0:00:02
   ------------------- -------------------- 1.3/2.8 MB 940.9 kB/s eta 0:00:02
   ---------------------- ----------------- 1.6/2.8 MB 794.8 kB/s eta 0:00:02
   ------------------------------ --------- 2.1/2.8 MB 952.4 kB/s eta 0:00:01
   ---------------------------------- ----- 2.4/2.8 MB 1.0 MB/s eta 0:00:01
   ---------------------------------------- 2.8/2.8 MB 1.1 MB/s  0:00:03
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.12

In [25]:
import pandas as pd
from sqlalchemy import create_engine

username = 'postgres'
password = 'anjal'
host = 'localhost'
database = "customer_behavior"

engine = create_engine(
    f"postgresql://{username}:{password}@{host}:5432/{database}"
)
table_name = 'customer'
df.to_sql(table_name ,engine , if_exists='replace',index=False)

900